name: Fetch Upstream
on:	
  schedule:	
     # actually, ~5 minutes is the highest	
     # effective frequency you will get	
    - cron:  '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git-version
      run: git version
    - name: Git-set-user
      run: git config --global user.name 'ohaddahan'	
    - name: Git-set-email
      run:  git config --global user.email 'ohaddahan@users.noreply.github.com'	
    - name: Git-checkout-master
      run: git checkout master	
    - name: Git-fetch-all
      run: git fetch --prune --unshallow
    - name: Git-remote-add
      run: git remote add upstream https://github.com/rust-lang/docs.rs.git
    - name: Git-fetch-upstream
      run: git fetch upstream	
    - name: Git-checkout-master-2
      run: git checkout master	
    - name: Git-merge
      run: git merge --no-edit upstream/master	
    - name: Git-push
      run: git push --set-upstream origin master
